# Generated by Django 5.0.2 on 2024-03-03 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price_min', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_max', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nb_like_min', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nb_like_max', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('algo_filtrage', models.BooleanField(default=True)),
                ('mode_tri', models.CharField(choices=[('PRICEASC', 'Tri par prix - +'), ('MOSTRECENT', "Les plus récents d'abord")], max_length=50)),
            ],
        ),
    ]
