# Generated by Django 4.2.9 on 2024-01-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='order',
            field=models.CharField(choices=[('NEWEST', 'NEWEST'), ('RELEVANCE', 'RELEVANCE'), ('LOWTOHIGH', 'LOWTOHIGH'), ('HIGHTOLOW', 'HIGHTOLOW')], max_length=60),
        ),
    ]
