# Generated by Django 4.2.9 on 2024-01-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters_manager', '0005_alter_article_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sizes',
            field=models.JSONField(),
        ),
    ]
