# Generated by Django 4.2.9 on 2024-01-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters_manager', '0007_alter_article_colors_alter_article_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='colors',
            field=models.JSONField(default={'BLACK': '', 'BLUE': '', 'GREEN': '', 'GREY': '', 'PURPLE': '', 'WHITE': '', 'YELLOW': ''}),
        ),
        migrations.AlterField(
            model_name='article',
            name='sizes',
            field=models.JSONField(default={'CHILDREN': ['10A', '11A', '12A', '13A', '14A', '15A', '16A'], 'MEN': ['XS', 'S', 'M', 'L', 'XL'], 'WOMEN': ['XXS', 'XXS', 'XS', 'S', 'M', 'L', 'XL']}),
        ),
    ]
