# Generated by Django 4.2.9 on 2024-01-13 10:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filters_manager', '0010_alter_article_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MEN,XS', 'MEN,XS'), ('MEN,S', 'MEN,S'), ('MEN,M', 'MEN,M'), ('MEN,L', 'MEN,L'), ('MEN,XL', 'MEN,XL'), ('WOMEN,XXS', 'WOMEN,XXS'), ('WOMEN,XXS', 'WOMEN,XXS'), ('WOMEN,XS', 'WOMEN,XS'), ('WOMEN,S', 'WOMEN,S'), ('WOMEN,M', 'WOMEN,M'), ('WOMEN,L', 'WOMEN,L'), ('WOMEN,XL', 'WOMEN,XL'), ('CHILDREN,10A', 'CHILDREN,10A'), ('CHILDREN,11A', 'CHILDREN,11A'), ('CHILDREN,12A', 'CHILDREN,12A'), ('CHILDREN,13A', 'CHILDREN,13A'), ('CHILDREN,14A', 'CHILDREN,14A'), ('CHILDREN,15A', 'CHILDREN,15A'), ('CHILDREN,16A', 'CHILDREN,16A')], max_length=12),
        ),
    ]
